theme: jekyll-theme-slate
title: Пользовательская документация по работе с HubEx
description: Краткие иснтрукции по работе, основные понятия и первые шаги по освоению платформы.
url: hubex.ru
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
